name: ci-cd
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog Secret Scan
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/repo" \
            ghcr.io/trufflesecurity/trufflehog:latest \
            git file:///repo \
            --no-update \
            --fail

  sast:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Semgrep
        run: semgrep scan --config p/default --error
